# -*- coding: utf-8 -*-
"""tratamento_olist_orders.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lq4cJJkLOjwOYHtFoYmsKxtRyCILmPHR
"""

import pandas as pd
import os

df = pd.read_csv('olist_orders_dataset.csv')
print(df.head())

df = df.dropna(subset=['order_id', 'customer_id', 'order_status'])

# 4. Converter colunas de data
df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])

# 5. Criar a pasta 'dados_tratados' se não existir
os.makedirs('dados_tratados', exist_ok=True)

# 6. Salvar arquivo tratado
df.to_csv('dados_tratados/olist_orders_tratado.csv', index=False)
print("✅ Arquivo tratado salvo com sucesso!")

"""# Tratamento olist_customers_dataset


"""

df_clientes = pd.read_csv("olist_customers_dataset.csv")

dim_cliente = df_clientes[[
    "customer_id",
    "customer_unique_id",
    "customer_city",
    "customer_state"
]].drop_duplicates()

os.makedirs("dimensoes", exist_ok=True)
dim_cliente.to_csv("dimensoes/dim_cliente.csv", index=False)

"""# Tratamento olist_products_dataset"""

df_prod = pd.read_csv("olist_products_dataset.csv")

df_cat = pd.read_csv("product_category_name_translation.csv")

dim_produto = df_prod.merge(df_cat, how="left", on="product_category_name")
dim_produto = dim_produto[[
    "product_id",
    "product_category_name",
    "product_category_name_english",
    "product_name_lenght",
    "product_description_lenght",
    "product_weight_g"
]].drop_duplicates()

os.makedirs("dimensoes", exist_ok=True)
dim_produto.to_csv("dimensoes/dim_produto.csv", index=False)

"""# Tratamento olist_sellers_dataset"""

df_sellers = pd.read_csv("olist_sellers_dataset.csv")

dim_vendedor = df_sellers[[
    "seller_id",
    "seller_city",
    "seller_state"
]].drop_duplicates()

os.makedirs("dimensoes", exist_ok=True)

dim_vendedor.to_csv("dimensoes/dim_vendedor.csv", index=False)

"""# Tratamento olist_orders_dataset"""

df_orders = pd.read_csv("olist_orders_dataset.csv")

dim_tempo = df_orders[["order_purchase_timestamp"]].dropna().drop_duplicates()
dim_tempo["data"] = pd.to_datetime(dim_tempo["order_purchase_timestamp"]).dt.date
dim_tempo["ano"] = pd.to_datetime(dim_tempo["order_purchase_timestamp"]).dt.year
dim_tempo["mes"] = pd.to_datetime(dim_tempo["order_purchase_timestamp"]).dt.month
dim_tempo["dia"] = pd.to_datetime(dim_tempo["order_purchase_timestamp"]).dt.day
dim_tempo["dia_semana"] = pd.to_datetime(dim_tempo["order_purchase_timestamp"]).dt.day_name()
dim_tempo["trimestre"] = pd.to_datetime(dim_tempo["order_purchase_timestamp"]).dt.quarter

dim_tempo = dim_tempo.drop(columns=["order_purchase_timestamp"]).drop_duplicates()

os.makedirs("dimensoes", exist_ok=True)
dim_tempo.to_csv("dimensoes/dim_tempo.csv", index=False)

# etl_fato_vendas

df_items = pd.read_csv("olist_order_items_dataset.csv")
df_orders = pd.read_csv("olist_orders_dataset.csv")
df_payments = pd.read_csv("olist_order_payments_dataset.csv")
df_reviews = pd.read_csv("olist_order_reviews_dataset.csv")

# Join principal: order_items + orders + customer_id
fato_vendas = df_items.merge(df_orders[['order_id', 'customer_id', 'order_purchase_timestamp', 'order_delivered_customer_date']], 
                             on="order_id", how="left")

# Pagamentos: usar apenas um tipo por pedido
df_pagamentos_unicos = df_payments.drop_duplicates(subset=["order_id"])
fato_vendas = fato_vendas.merge(df_pagamentos_unicos, on="order_id", how="left")

# Reviews: nota da avaliação
df_reviews_simples = df_reviews[["order_id", "review_score"]].drop_duplicates()
fato_vendas = fato_vendas.merge(df_reviews_simples, on="order_id", how="left")

# Seleciona colunas da fato (agora inclui customer_id)
fato_vendas = fato_vendas[[
    "order_id",
    "customer_id",
    "order_item_id",
    "product_id",
    "seller_id",
    "price",
    "freight_value",
    "payment_type",
    "payment_value",
    "review_score",
    "order_purchase_timestamp",
    "order_delivered_customer_date"
]]

# Salvar o arquivo corrigido
fato_vendas.to_csv("fato_vendas.csv", index=False)


# Faz o download para sua máquina
from google.colab import files
files.download("fato_vendas.csv")

















